-- Create categories table if not exists
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon_url text,
  type text check (type in ('product', 'service', 'both')) default 'both',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table categories enable row level security;

drop policy if exists "Categories are viewable by everyone." on categories;
create policy "Categories are viewable by everyone." on categories for select using (true);

drop policy if exists "Admins can insert categories" on categories;
create policy "Admins can insert categories" on categories for insert with check (
  auth.role() = 'service_role' or 
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists "Admins can update categories" on categories;
create policy "Admins can update categories" on categories for update using (
  auth.role() = 'service_role' or 
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists "Admins can delete categories" on categories;
create policy "Admins can delete categories" on categories for delete using (
  auth.role() = 'service_role' or 
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Storage
insert into storage.buckets (id, name, public) values ('categories', 'categories', true) on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('site-assets', 'site-assets', true) on conflict (id) do nothing;

drop policy if exists "Public Access" on storage.objects;
create policy "Public Access" on storage.objects for select using ( bucket_id in ('categories', 'site-assets') );

drop policy if exists "Admin Upload" on storage.objects;
create policy "Admin Upload" on storage.objects for insert with check ( 
  bucket_id in ('categories', 'site-assets') and 
  (auth.role() = 'service_role' or exists (select 1 from profiles where id = auth.uid() and role = 'admin')) 
);

drop policy if exists "Admin Update" on storage.objects;
create policy "Admin Update" on storage.objects for update using ( 
  bucket_id in ('categories', 'site-assets') and 
  (auth.role() = 'service_role' or exists (select 1 from profiles where id = auth.uid() and role = 'admin')) 
);

-- Default Site Settings
insert into site_settings (key, value, description) values
('hero', '{"type": "color", "value": "bg-primary", "image_url": null}'::jsonb, 'Hero section settings'),
('login_banner', '{"image_url": "https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=2832&auto=format&fit=crop"}'::jsonb, 'Login page banner image')
on conflict (key) do nothing;
